### ISSUE TITLE
wails build error message

### ISSUE THREAD

**Issue by zhuewizz** [HumXC/give-me-genshin-gacha#2]
Building target: windows/amd64
------------------------------
  - Generating bindings: Done.
  - Installing frontend dependencies: Done.
  - Compiling frontend:
    npm ERR! code ENOENT
    npm ERR! syscall open
    npm ERR! path D:\postgrest\give-me-genshin-gacha\frontend/package.json
    npm ERR! errno -4058
    npm ERR! enoent ENOENT: no such file or directory, open 'D:\postgrest\give-me-genshin-gacha\frontend\package.json'
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\zhuweizz\AppData\Local\npm-cache\_logs\2022-12-26T04_34_56_791Z-debug-0.log

Error: exit status 0xfffff026

ERROR: exit status 0xfffff026

**Comment by HumXC** [comment]
是因为我把前端项目的 package.josn 在 git 中忽略了，已经在[此提交](https://github.com/HumXC/give-me-genshin-gacha/commit/7e844bce6e9652fbbcbaca548b1862eaa270193e)中被修复

**Comment by zhuewizz** [comment]
谢谢



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/26/2022 14:15 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HumXC/give-me-genshin-gacha] wails build error message (Issue #2) |

Closed #2 as completed.
